site_name: HPC Cost Simulator
repo_url: https://github.com/aws-samples/hpc-cost-simulator
docs_dir: docs
nav:
  - 'index.md'
  - 'AcceleratorLogParser.md'
  - 'LSFLogParser.md'
  - 'SlurmLogParser.md'
  - 'JsonLogParser.md'
  - 'JobAnalyzer.md'
  - 'Output.md'
  - 'config.md'
  - 'model-scheduling.md'
strict: true
theme:
  name: mkdocs
  #name: readthedocs
  hljs_languages:
    - python
    - yaml
  navigation_depth: 4
  nav_style: dark
  features:
    - navigation.tabs
